# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4657307494b16a337525b411315494980d886710a42b6e0f22b398c3a8e8716193b07c594f00424738f498c323ed5b8ef8d810ee7fee068711aa49996fb73130

test:
  secret_key_base: 6afc290048e0c34c79313c29b4fc3eaf83f9d853bdcf62c8b5b1bc00e22841356647a78b6e8493a236e9799214c130e3ebbfe9adb2f37bf2a20dd39bbb5c5cc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
